Fix setup issues in TensorMap
scorelab/tensormap pull request #187
Opened 2023-06-01 17:49 UTC by Wenuka19

# Description

In this pull request following issues are addressed.
1.  Multiple incompatibility warnings appearing at `tensormap-client` .  `BadCommandError` due to `--openssl-legacy-provider` command at `npm start`
2.  `tensormap-server` fails at certain points due to missing dependencies in `requirements.txt`
3.  Filename incompatibilities in the database and the local storage of data files.

Fixes
1.  Updated the versions of packages used in `tensormap-client` on `package.json`
2.  Added all the missing requirements into the `requirements.txt` file
3.  Used same conditions to filenames when saving to database and to local storage

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

The setup process is thoroughly tested a windows and a Linux environment. After applying the changes there were less vulnerability warnings at the `tensormap-client` and no warnings or missing dependency errors in `tensormap-server`.

- [x] Test A : Try setting up both `tensormap-client` and `tensormap-server` from the beginning by following the instructions given. There will not be any dependencies missing & the apps should run with no issue.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2023-06-05 18:20 UTC, ivantha requested changes

2023-06-05 18:20 UTC, ivantha commented on tensormap-client/.gitignore
> +package-lock.json
This should not be ignored.

2023-06-06 01:28 UTC, Wenuka19 commented on tensormap-client/.gitignore
> +package-lock.json
I fixed it. Please check now.

2023-06-06 01:47 UTC, ivantha approved these changes

2023-06-06 01:47 UTC, merged